namespace DBMS1.FTable
{
    partial class FBoPhim
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FBoPhim));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.dgvBoPhim = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.flowLayoutPanel1 = new System.Windows.Forms.FlowLayoutPanel();
            this.flowLayoutPanel2 = new System.Windows.Forms.FlowLayoutPanel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.label8 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label4 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.btnXoa = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnUpdate = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnThem = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.txtTomTat = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDienVien = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtDaoDien = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtThoiLuong = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTheLoai = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtTenBoPhim = new Bunifu.UI.WinForms.BunifuTextBox();
            this.txtMaBoPhim = new Bunifu.UI.WinForms.BunifuTextBox();
            ((System.ComponentModel.ISupportInitialize)(this.dgvBoPhim)).BeginInit();
            this.flowLayoutPanel1.SuspendLayout();
            this.flowLayoutPanel2.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.SuspendLayout();
            // 
            // dgvBoPhim
            // 
            this.dgvBoPhim.AllowCustomTheming = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.dgvBoPhim.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.dgvBoPhim.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvBoPhim.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.dgvBoPhim.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.dgvBoPhim.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.dgvBoPhim.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.dgvBoPhim.ColumnHeadersHeight = 40;
            this.dgvBoPhim.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.dgvBoPhim.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvBoPhim.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvBoPhim.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvBoPhim.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.dgvBoPhim.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.dgvBoPhim.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvBoPhim.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.dgvBoPhim.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.dgvBoPhim.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.dgvBoPhim.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.dgvBoPhim.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.dgvBoPhim.CurrentTheme.Name = null;
            this.dgvBoPhim.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.dgvBoPhim.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.dgvBoPhim.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.dgvBoPhim.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.dgvBoPhim.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.dgvBoPhim.DefaultCellStyle = dataGridViewCellStyle3;
            this.dgvBoPhim.EnableHeadersVisualStyles = false;
            this.dgvBoPhim.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.dgvBoPhim.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.dgvBoPhim.HeaderBgColor = System.Drawing.Color.Empty;
            this.dgvBoPhim.HeaderForeColor = System.Drawing.Color.White;
            this.dgvBoPhim.Location = new System.Drawing.Point(3, 3);
            this.dgvBoPhim.Name = "dgvBoPhim";
            this.dgvBoPhim.RowHeadersVisible = false;
            this.dgvBoPhim.RowHeadersWidth = 51;
            this.dgvBoPhim.RowTemplate.Height = 40;
            this.dgvBoPhim.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvBoPhim.Size = new System.Drawing.Size(1313, 430);
            this.dgvBoPhim.TabIndex = 1;
            this.dgvBoPhim.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            this.dgvBoPhim.CellContentClick += new System.Windows.Forms.DataGridViewCellEventHandler(this.dgvBoPhim_CellContentClick);
            // 
            // flowLayoutPanel1
            // 
            this.flowLayoutPanel1.Controls.Add(this.dgvBoPhim);
            this.flowLayoutPanel1.Location = new System.Drawing.Point(12, 292);
            this.flowLayoutPanel1.Name = "flowLayoutPanel1";
            this.flowLayoutPanel1.Size = new System.Drawing.Size(1316, 433);
            this.flowLayoutPanel1.TabIndex = 3;
            // 
            // flowLayoutPanel2
            // 
            this.flowLayoutPanel2.Controls.Add(this.bunifuShadowPanel1);
            this.flowLayoutPanel2.Location = new System.Drawing.Point(242, 12);
            this.flowLayoutPanel2.Name = "flowLayoutPanel2";
            this.flowLayoutPanel2.Size = new System.Drawing.Size(989, 283);
            this.flowLayoutPanel2.TabIndex = 4;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.DodgerBlue;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.label8);
            this.bunifuShadowPanel1.Controls.Add(this.label7);
            this.bunifuShadowPanel1.Controls.Add(this.label6);
            this.bunifuShadowPanel1.Controls.Add(this.label4);
            this.bunifuShadowPanel1.Controls.Add(this.label3);
            this.bunifuShadowPanel1.Controls.Add(this.label1);
            this.bunifuShadowPanel1.Controls.Add(this.label2);
            this.bunifuShadowPanel1.Controls.Add(this.label5);
            this.bunifuShadowPanel1.Controls.Add(this.btnXoa);
            this.bunifuShadowPanel1.Controls.Add(this.btnUpdate);
            this.bunifuShadowPanel1.Controls.Add(this.btnThem);
            this.bunifuShadowPanel1.Controls.Add(this.txtTomTat);
            this.bunifuShadowPanel1.Controls.Add(this.txtDienVien);
            this.bunifuShadowPanel1.Controls.Add(this.txtDaoDien);
            this.bunifuShadowPanel1.Controls.Add(this.txtThoiLuong);
            this.bunifuShadowPanel1.Controls.Add(this.txtTheLoai);
            this.bunifuShadowPanel1.Controls.Add(this.txtTenBoPhim);
            this.bunifuShadowPanel1.Controls.Add(this.txtMaBoPhim);
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(3, 3);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.WhiteSmoke;
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.DodgerBlue;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 5;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Surrounded;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(985, 275);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // label8
            // 
            this.label8.AutoSize = true;
            this.label8.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.label8.Location = new System.Drawing.Point(424, 162);
            this.label8.Name = "label8";
            this.label8.Size = new System.Drawing.Size(91, 24);
            this.label8.TabIndex = 91;
            this.label8.Text = "Đạo Diễn";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.label7.Location = new System.Drawing.Point(424, 120);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(79, 24);
            this.label7.TabIndex = 90;
            this.label7.Text = "Tóm Tắt";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.label6.Location = new System.Drawing.Point(424, 74);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(94, 24);
            this.label6.TabIndex = 89;
            this.label6.Text = "Diễn Viên";
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.label4.Location = new System.Drawing.Point(40, 201);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(108, 24);
            this.label4.TabIndex = 88;
            this.label4.Text = "Thời Lượng";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.label3.Location = new System.Drawing.Point(40, 114);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(120, 24);
            this.label3.TabIndex = 87;
            this.label3.Text = "Tên Bộ Phim";
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.label1.Location = new System.Drawing.Point(42, 160);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(85, 24);
            this.label1.TabIndex = 86;
            this.label1.Text = "Thể Loại";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.label2.Location = new System.Drawing.Point(40, 66);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(116, 24);
            this.label2.TabIndex = 85;
            this.label2.Text = "Mã Bộ Phim";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Font = new System.Drawing.Font("Bahnschrift SemiBold", 20F, System.Drawing.FontStyle.Bold);
            this.label5.Location = new System.Drawing.Point(321, 9);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(150, 41);
            this.label5.TabIndex = 84;
            this.label5.Text = "BỘ PHIM";
            // 
            // btnXoa
            // 
            this.btnXoa.AllowAnimations = true;
            this.btnXoa.AllowMouseEffects = true;
            this.btnXoa.AllowToggling = false;
            this.btnXoa.AnimationSpeed = 200;
            this.btnXoa.AutoGenerateColors = false;
            this.btnXoa.AutoRoundBorders = false;
            this.btnXoa.AutoSizeLeftIcon = true;
            this.btnXoa.AutoSizeRightIcon = true;
            this.btnXoa.BackColor = System.Drawing.Color.Transparent;
            this.btnXoa.BackColor1 = System.Drawing.Color.LightSkyBlue;
            this.btnXoa.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnXoa.BackgroundImage")));
            this.btnXoa.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.ButtonText = "Xóa";
            this.btnXoa.ButtonTextMarginLeft = 0;
            this.btnXoa.ColorContrastOnClick = 45;
            this.btnXoa.ColorContrastOnHover = 45;
            this.btnXoa.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnXoa.CustomizableEdges = borderEdges1;
            this.btnXoa.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnXoa.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnXoa.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.btnXoa.ForeColor = System.Drawing.Color.White;
            this.btnXoa.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnXoa.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnXoa.IconMarginLeft = 11;
            this.btnXoa.IconPadding = 10;
            this.btnXoa.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnXoa.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnXoa.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnXoa.IconSize = 25;
            this.btnXoa.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnXoa.IdleBorderRadius = 5;
            this.btnXoa.IdleBorderThickness = 2;
            this.btnXoa.IdleFillColor = System.Drawing.Color.LightSkyBlue;
            this.btnXoa.IdleIconLeftImage = null;
            this.btnXoa.IdleIconRightImage = null;
            this.btnXoa.IndicateFocus = false;
            this.btnXoa.Location = new System.Drawing.Point(491, 201);
            this.btnXoa.Name = "btnXoa";
            this.btnXoa.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnXoa.OnDisabledState.BorderRadius = 5;
            this.btnXoa.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnDisabledState.BorderThickness = 2;
            this.btnXoa.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnXoa.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnXoa.OnDisabledState.IconLeftImage = null;
            this.btnXoa.OnDisabledState.IconRightImage = null;
            this.btnXoa.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXoa.onHoverState.BorderRadius = 5;
            this.btnXoa.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.onHoverState.BorderThickness = 2;
            this.btnXoa.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnXoa.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.onHoverState.IconLeftImage = null;
            this.btnXoa.onHoverState.IconRightImage = null;
            this.btnXoa.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnXoa.OnIdleState.BorderRadius = 5;
            this.btnXoa.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnIdleState.BorderThickness = 2;
            this.btnXoa.OnIdleState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnXoa.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.OnIdleState.IconLeftImage = null;
            this.btnXoa.OnIdleState.IconRightImage = null;
            this.btnXoa.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoa.OnPressedState.BorderRadius = 5;
            this.btnXoa.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnXoa.OnPressedState.BorderThickness = 2;
            this.btnXoa.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnXoa.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnXoa.OnPressedState.IconLeftImage = null;
            this.btnXoa.OnPressedState.IconRightImage = null;
            this.btnXoa.Size = new System.Drawing.Size(125, 51);
            this.btnXoa.TabIndex = 43;
            this.btnXoa.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnXoa.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnXoa.TextMarginLeft = 0;
            this.btnXoa.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnXoa.UseDefaultRadiusAndThickness = true;
            this.btnXoa.Click += new System.EventHandler(this.btnXoa_Click);
            // 
            // btnUpdate
            // 
            this.btnUpdate.AllowAnimations = true;
            this.btnUpdate.AllowMouseEffects = true;
            this.btnUpdate.AllowToggling = false;
            this.btnUpdate.AnimationSpeed = 200;
            this.btnUpdate.AutoGenerateColors = false;
            this.btnUpdate.AutoRoundBorders = false;
            this.btnUpdate.AutoSizeLeftIcon = true;
            this.btnUpdate.AutoSizeRightIcon = true;
            this.btnUpdate.BackColor = System.Drawing.Color.Transparent;
            this.btnUpdate.BackColor1 = System.Drawing.Color.LightSkyBlue;
            this.btnUpdate.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnUpdate.BackgroundImage")));
            this.btnUpdate.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.ButtonText = "Cập nhật";
            this.btnUpdate.ButtonTextMarginLeft = 0;
            this.btnUpdate.ColorContrastOnClick = 45;
            this.btnUpdate.ColorContrastOnHover = 45;
            this.btnUpdate.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnUpdate.CustomizableEdges = borderEdges2;
            this.btnUpdate.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnUpdate.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnUpdate.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.btnUpdate.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnUpdate.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnUpdate.IconMarginLeft = 11;
            this.btnUpdate.IconPadding = 10;
            this.btnUpdate.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnUpdate.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnUpdate.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnUpdate.IconSize = 25;
            this.btnUpdate.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnUpdate.IdleBorderRadius = 5;
            this.btnUpdate.IdleBorderThickness = 2;
            this.btnUpdate.IdleFillColor = System.Drawing.Color.LightSkyBlue;
            this.btnUpdate.IdleIconLeftImage = null;
            this.btnUpdate.IdleIconRightImage = null;
            this.btnUpdate.IndicateFocus = false;
            this.btnUpdate.Location = new System.Drawing.Point(636, 201);
            this.btnUpdate.Name = "btnUpdate";
            this.btnUpdate.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnUpdate.OnDisabledState.BorderRadius = 5;
            this.btnUpdate.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnDisabledState.BorderThickness = 2;
            this.btnUpdate.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnUpdate.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnUpdate.OnDisabledState.IconLeftImage = null;
            this.btnUpdate.OnDisabledState.IconRightImage = null;
            this.btnUpdate.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpdate.onHoverState.BorderRadius = 5;
            this.btnUpdate.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.onHoverState.BorderThickness = 2;
            this.btnUpdate.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnUpdate.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.onHoverState.IconLeftImage = null;
            this.btnUpdate.onHoverState.IconRightImage = null;
            this.btnUpdate.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnUpdate.OnIdleState.BorderRadius = 5;
            this.btnUpdate.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnIdleState.BorderThickness = 2;
            this.btnUpdate.OnIdleState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnUpdate.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnIdleState.IconLeftImage = null;
            this.btnUpdate.OnIdleState.IconRightImage = null;
            this.btnUpdate.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpdate.OnPressedState.BorderRadius = 5;
            this.btnUpdate.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnUpdate.OnPressedState.BorderThickness = 2;
            this.btnUpdate.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnUpdate.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnUpdate.OnPressedState.IconLeftImage = null;
            this.btnUpdate.OnPressedState.IconRightImage = null;
            this.btnUpdate.Size = new System.Drawing.Size(125, 51);
            this.btnUpdate.TabIndex = 43;
            this.btnUpdate.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnUpdate.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnUpdate.TextMarginLeft = 0;
            this.btnUpdate.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnUpdate.UseDefaultRadiusAndThickness = true;
            this.btnUpdate.Click += new System.EventHandler(this.btnUpdate_Click);
            // 
            // btnThem
            // 
            this.btnThem.AllowAnimations = true;
            this.btnThem.AllowMouseEffects = true;
            this.btnThem.AllowToggling = false;
            this.btnThem.AnimationSpeed = 200;
            this.btnThem.AutoGenerateColors = false;
            this.btnThem.AutoRoundBorders = false;
            this.btnThem.AutoSizeLeftIcon = true;
            this.btnThem.AutoSizeRightIcon = true;
            this.btnThem.BackColor = System.Drawing.Color.Transparent;
            this.btnThem.BackColor1 = System.Drawing.Color.LightSkyBlue;
            this.btnThem.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThem.BackgroundImage")));
            this.btnThem.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.ButtonText = "Thêm";
            this.btnThem.ButtonTextMarginLeft = 0;
            this.btnThem.ColorContrastOnClick = 45;
            this.btnThem.ColorContrastOnHover = 45;
            this.btnThem.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnThem.CustomizableEdges = borderEdges3;
            this.btnThem.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThem.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.btnThem.Font = new System.Drawing.Font("Segoe UI", 12F, System.Drawing.FontStyle.Bold);
            this.btnThem.ForeColor = System.Drawing.Color.White;
            this.btnThem.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThem.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThem.IconMarginLeft = 11;
            this.btnThem.IconPadding = 10;
            this.btnThem.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThem.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThem.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThem.IconSize = 25;
            this.btnThem.IdleBorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnThem.IdleBorderRadius = 5;
            this.btnThem.IdleBorderThickness = 2;
            this.btnThem.IdleFillColor = System.Drawing.Color.LightSkyBlue;
            this.btnThem.IdleIconLeftImage = null;
            this.btnThem.IdleIconRightImage = null;
            this.btnThem.IndicateFocus = false;
            this.btnThem.Location = new System.Drawing.Point(359, 201);
            this.btnThem.Name = "btnThem";
            this.btnThem.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThem.OnDisabledState.BorderRadius = 5;
            this.btnThem.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnDisabledState.BorderThickness = 2;
            this.btnThem.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThem.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThem.OnDisabledState.IconLeftImage = null;
            this.btnThem.OnDisabledState.IconRightImage = null;
            this.btnThem.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.BorderRadius = 5;
            this.btnThem.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.onHoverState.BorderThickness = 2;
            this.btnThem.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThem.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThem.onHoverState.IconLeftImage = null;
            this.btnThem.onHoverState.IconRightImage = null;
            this.btnThem.OnIdleState.BorderColor = System.Drawing.Color.DeepSkyBlue;
            this.btnThem.OnIdleState.BorderRadius = 5;
            this.btnThem.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnIdleState.BorderThickness = 2;
            this.btnThem.OnIdleState.FillColor = System.Drawing.Color.LightSkyBlue;
            this.btnThem.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnIdleState.IconLeftImage = null;
            this.btnThem.OnIdleState.IconRightImage = null;
            this.btnThem.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.BorderRadius = 5;
            this.btnThem.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThem.OnPressedState.BorderThickness = 2;
            this.btnThem.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThem.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThem.OnPressedState.IconLeftImage = null;
            this.btnThem.OnPressedState.IconRightImage = null;
            this.btnThem.Size = new System.Drawing.Size(125, 51);
            this.btnThem.TabIndex = 42;
            this.btnThem.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.btnThem.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThem.TextMarginLeft = 0;
            this.btnThem.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThem.UseDefaultRadiusAndThickness = true;
            this.btnThem.Click += new System.EventHandler(this.btnThem_Click);
            // 
            // txtTomTat
            // 
            this.txtTomTat.AcceptsReturn = false;
            this.txtTomTat.AcceptsTab = false;
            this.txtTomTat.AnimationSpeed = 200;
            this.txtTomTat.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTomTat.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTomTat.BackColor = System.Drawing.Color.Transparent;
            this.txtTomTat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTomTat.BackgroundImage")));
            this.txtTomTat.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTomTat.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTomTat.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTomTat.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTomTat.BorderRadius = 1;
            this.txtTomTat.BorderThickness = 1;
            this.txtTomTat.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTomTat.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTomTat.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTomTat.DefaultText = "";
            this.txtTomTat.FillColor = System.Drawing.Color.White;
            this.txtTomTat.HideSelection = true;
            this.txtTomTat.IconLeft = null;
            this.txtTomTat.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTomTat.IconPadding = 10;
            this.txtTomTat.IconRight = null;
            this.txtTomTat.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTomTat.Lines = new string[0];
            this.txtTomTat.Location = new System.Drawing.Point(536, 116);
            this.txtTomTat.MaxLength = 32767;
            this.txtTomTat.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTomTat.Modified = false;
            this.txtTomTat.Multiline = false;
            this.txtTomTat.Name = "txtTomTat";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTomTat.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTomTat.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTomTat.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTomTat.OnIdleState = stateProperties4;
            this.txtTomTat.Padding = new System.Windows.Forms.Padding(3);
            this.txtTomTat.PasswordChar = '\0';
            this.txtTomTat.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTomTat.PlaceholderText = "Enter text";
            this.txtTomTat.ReadOnly = false;
            this.txtTomTat.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTomTat.SelectedText = "";
            this.txtTomTat.SelectionLength = 0;
            this.txtTomTat.SelectionStart = 0;
            this.txtTomTat.ShortcutsEnabled = true;
            this.txtTomTat.Size = new System.Drawing.Size(172, 33);
            this.txtTomTat.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTomTat.TabIndex = 41;
            this.txtTomTat.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTomTat.TextMarginBottom = 0;
            this.txtTomTat.TextMarginLeft = 3;
            this.txtTomTat.TextMarginTop = 0;
            this.txtTomTat.TextPlaceholder = "Enter text";
            this.txtTomTat.UseSystemPasswordChar = false;
            this.txtTomTat.WordWrap = true;
            // 
            // txtDienVien
            // 
            this.txtDienVien.AcceptsReturn = false;
            this.txtDienVien.AcceptsTab = false;
            this.txtDienVien.AnimationSpeed = 200;
            this.txtDienVien.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDienVien.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDienVien.BackColor = System.Drawing.Color.Transparent;
            this.txtDienVien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDienVien.BackgroundImage")));
            this.txtDienVien.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDienVien.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDienVien.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDienVien.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDienVien.BorderRadius = 1;
            this.txtDienVien.BorderThickness = 1;
            this.txtDienVien.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDienVien.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDienVien.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDienVien.DefaultText = "";
            this.txtDienVien.FillColor = System.Drawing.Color.White;
            this.txtDienVien.HideSelection = true;
            this.txtDienVien.IconLeft = null;
            this.txtDienVien.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDienVien.IconPadding = 10;
            this.txtDienVien.IconRight = null;
            this.txtDienVien.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDienVien.Lines = new string[0];
            this.txtDienVien.Location = new System.Drawing.Point(536, 65);
            this.txtDienVien.MaxLength = 32767;
            this.txtDienVien.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDienVien.Modified = false;
            this.txtDienVien.Multiline = false;
            this.txtDienVien.Name = "txtDienVien";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDienVien.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDienVien.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDienVien.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDienVien.OnIdleState = stateProperties8;
            this.txtDienVien.Padding = new System.Windows.Forms.Padding(3);
            this.txtDienVien.PasswordChar = '\0';
            this.txtDienVien.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDienVien.PlaceholderText = "Enter text";
            this.txtDienVien.ReadOnly = false;
            this.txtDienVien.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDienVien.SelectedText = "";
            this.txtDienVien.SelectionLength = 0;
            this.txtDienVien.SelectionStart = 0;
            this.txtDienVien.ShortcutsEnabled = true;
            this.txtDienVien.Size = new System.Drawing.Size(172, 33);
            this.txtDienVien.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDienVien.TabIndex = 39;
            this.txtDienVien.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDienVien.TextMarginBottom = 0;
            this.txtDienVien.TextMarginLeft = 3;
            this.txtDienVien.TextMarginTop = 0;
            this.txtDienVien.TextPlaceholder = "Enter text";
            this.txtDienVien.UseSystemPasswordChar = false;
            this.txtDienVien.WordWrap = true;
            // 
            // txtDaoDien
            // 
            this.txtDaoDien.AcceptsReturn = false;
            this.txtDaoDien.AcceptsTab = false;
            this.txtDaoDien.AnimationSpeed = 200;
            this.txtDaoDien.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtDaoDien.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtDaoDien.BackColor = System.Drawing.Color.Transparent;
            this.txtDaoDien.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtDaoDien.BackgroundImage")));
            this.txtDaoDien.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtDaoDien.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtDaoDien.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtDaoDien.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtDaoDien.BorderRadius = 1;
            this.txtDaoDien.BorderThickness = 1;
            this.txtDaoDien.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtDaoDien.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDaoDien.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtDaoDien.DefaultText = "";
            this.txtDaoDien.FillColor = System.Drawing.Color.White;
            this.txtDaoDien.HideSelection = true;
            this.txtDaoDien.IconLeft = null;
            this.txtDaoDien.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDaoDien.IconPadding = 10;
            this.txtDaoDien.IconRight = null;
            this.txtDaoDien.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtDaoDien.Lines = new string[0];
            this.txtDaoDien.Location = new System.Drawing.Point(536, 162);
            this.txtDaoDien.MaxLength = 32767;
            this.txtDaoDien.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtDaoDien.Modified = false;
            this.txtDaoDien.Multiline = false;
            this.txtDaoDien.Name = "txtDaoDien";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDaoDien.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtDaoDien.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDaoDien.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtDaoDien.OnIdleState = stateProperties12;
            this.txtDaoDien.Padding = new System.Windows.Forms.Padding(3);
            this.txtDaoDien.PasswordChar = '\0';
            this.txtDaoDien.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtDaoDien.PlaceholderText = "Enter text";
            this.txtDaoDien.ReadOnly = false;
            this.txtDaoDien.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtDaoDien.SelectedText = "";
            this.txtDaoDien.SelectionLength = 0;
            this.txtDaoDien.SelectionStart = 0;
            this.txtDaoDien.ShortcutsEnabled = true;
            this.txtDaoDien.Size = new System.Drawing.Size(172, 33);
            this.txtDaoDien.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtDaoDien.TabIndex = 37;
            this.txtDaoDien.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtDaoDien.TextMarginBottom = 0;
            this.txtDaoDien.TextMarginLeft = 3;
            this.txtDaoDien.TextMarginTop = 0;
            this.txtDaoDien.TextPlaceholder = "Enter text";
            this.txtDaoDien.UseSystemPasswordChar = false;
            this.txtDaoDien.WordWrap = true;
            // 
            // txtThoiLuong
            // 
            this.txtThoiLuong.AcceptsReturn = false;
            this.txtThoiLuong.AcceptsTab = false;
            this.txtThoiLuong.AnimationSpeed = 200;
            this.txtThoiLuong.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtThoiLuong.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtThoiLuong.BackColor = System.Drawing.Color.Transparent;
            this.txtThoiLuong.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtThoiLuong.BackgroundImage")));
            this.txtThoiLuong.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtThoiLuong.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtThoiLuong.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtThoiLuong.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtThoiLuong.BorderRadius = 1;
            this.txtThoiLuong.BorderThickness = 1;
            this.txtThoiLuong.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtThoiLuong.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThoiLuong.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtThoiLuong.DefaultText = "";
            this.txtThoiLuong.FillColor = System.Drawing.Color.White;
            this.txtThoiLuong.HideSelection = true;
            this.txtThoiLuong.IconLeft = null;
            this.txtThoiLuong.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThoiLuong.IconPadding = 10;
            this.txtThoiLuong.IconRight = null;
            this.txtThoiLuong.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtThoiLuong.Lines = new string[0];
            this.txtThoiLuong.Location = new System.Drawing.Point(170, 201);
            this.txtThoiLuong.MaxLength = 32767;
            this.txtThoiLuong.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtThoiLuong.Modified = false;
            this.txtThoiLuong.Multiline = false;
            this.txtThoiLuong.Name = "txtThoiLuong";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThoiLuong.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtThoiLuong.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThoiLuong.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtThoiLuong.OnIdleState = stateProperties16;
            this.txtThoiLuong.Padding = new System.Windows.Forms.Padding(3);
            this.txtThoiLuong.PasswordChar = '\0';
            this.txtThoiLuong.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtThoiLuong.PlaceholderText = "Enter text";
            this.txtThoiLuong.ReadOnly = false;
            this.txtThoiLuong.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtThoiLuong.SelectedText = "";
            this.txtThoiLuong.SelectionLength = 0;
            this.txtThoiLuong.SelectionStart = 0;
            this.txtThoiLuong.ShortcutsEnabled = true;
            this.txtThoiLuong.Size = new System.Drawing.Size(172, 33);
            this.txtThoiLuong.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtThoiLuong.TabIndex = 35;
            this.txtThoiLuong.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtThoiLuong.TextMarginBottom = 0;
            this.txtThoiLuong.TextMarginLeft = 3;
            this.txtThoiLuong.TextMarginTop = 0;
            this.txtThoiLuong.TextPlaceholder = "Enter text";
            this.txtThoiLuong.UseSystemPasswordChar = false;
            this.txtThoiLuong.WordWrap = true;
            // 
            // txtTheLoai
            // 
            this.txtTheLoai.AcceptsReturn = false;
            this.txtTheLoai.AcceptsTab = false;
            this.txtTheLoai.AnimationSpeed = 200;
            this.txtTheLoai.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTheLoai.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTheLoai.BackColor = System.Drawing.Color.Transparent;
            this.txtTheLoai.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTheLoai.BackgroundImage")));
            this.txtTheLoai.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTheLoai.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTheLoai.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTheLoai.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTheLoai.BorderRadius = 1;
            this.txtTheLoai.BorderThickness = 1;
            this.txtTheLoai.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTheLoai.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTheLoai.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTheLoai.DefaultText = "";
            this.txtTheLoai.FillColor = System.Drawing.Color.White;
            this.txtTheLoai.HideSelection = true;
            this.txtTheLoai.IconLeft = null;
            this.txtTheLoai.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTheLoai.IconPadding = 10;
            this.txtTheLoai.IconRight = null;
            this.txtTheLoai.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTheLoai.Lines = new string[0];
            this.txtTheLoai.Location = new System.Drawing.Point(170, 156);
            this.txtTheLoai.MaxLength = 32767;
            this.txtTheLoai.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTheLoai.Modified = false;
            this.txtTheLoai.Multiline = false;
            this.txtTheLoai.Name = "txtTheLoai";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTheLoai.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTheLoai.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTheLoai.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTheLoai.OnIdleState = stateProperties20;
            this.txtTheLoai.Padding = new System.Windows.Forms.Padding(3);
            this.txtTheLoai.PasswordChar = '\0';
            this.txtTheLoai.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTheLoai.PlaceholderText = "Enter text";
            this.txtTheLoai.ReadOnly = false;
            this.txtTheLoai.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTheLoai.SelectedText = "";
            this.txtTheLoai.SelectionLength = 0;
            this.txtTheLoai.SelectionStart = 0;
            this.txtTheLoai.ShortcutsEnabled = true;
            this.txtTheLoai.Size = new System.Drawing.Size(172, 33);
            this.txtTheLoai.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTheLoai.TabIndex = 33;
            this.txtTheLoai.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTheLoai.TextMarginBottom = 0;
            this.txtTheLoai.TextMarginLeft = 3;
            this.txtTheLoai.TextMarginTop = 0;
            this.txtTheLoai.TextPlaceholder = "Enter text";
            this.txtTheLoai.UseSystemPasswordChar = false;
            this.txtTheLoai.WordWrap = true;
            // 
            // txtTenBoPhim
            // 
            this.txtTenBoPhim.AcceptsReturn = false;
            this.txtTenBoPhim.AcceptsTab = false;
            this.txtTenBoPhim.AnimationSpeed = 200;
            this.txtTenBoPhim.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtTenBoPhim.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtTenBoPhim.BackColor = System.Drawing.Color.Transparent;
            this.txtTenBoPhim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtTenBoPhim.BackgroundImage")));
            this.txtTenBoPhim.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtTenBoPhim.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtTenBoPhim.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtTenBoPhim.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtTenBoPhim.BorderRadius = 1;
            this.txtTenBoPhim.BorderThickness = 1;
            this.txtTenBoPhim.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtTenBoPhim.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenBoPhim.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtTenBoPhim.DefaultText = "";
            this.txtTenBoPhim.FillColor = System.Drawing.Color.White;
            this.txtTenBoPhim.HideSelection = true;
            this.txtTenBoPhim.IconLeft = null;
            this.txtTenBoPhim.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenBoPhim.IconPadding = 10;
            this.txtTenBoPhim.IconRight = null;
            this.txtTenBoPhim.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtTenBoPhim.Lines = new string[0];
            this.txtTenBoPhim.Location = new System.Drawing.Point(170, 111);
            this.txtTenBoPhim.MaxLength = 32767;
            this.txtTenBoPhim.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtTenBoPhim.Modified = false;
            this.txtTenBoPhim.Multiline = false;
            this.txtTenBoPhim.Name = "txtTenBoPhim";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenBoPhim.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtTenBoPhim.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenBoPhim.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtTenBoPhim.OnIdleState = stateProperties24;
            this.txtTenBoPhim.Padding = new System.Windows.Forms.Padding(3);
            this.txtTenBoPhim.PasswordChar = '\0';
            this.txtTenBoPhim.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtTenBoPhim.PlaceholderText = "Enter text";
            this.txtTenBoPhim.ReadOnly = false;
            this.txtTenBoPhim.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtTenBoPhim.SelectedText = "";
            this.txtTenBoPhim.SelectionLength = 0;
            this.txtTenBoPhim.SelectionStart = 0;
            this.txtTenBoPhim.ShortcutsEnabled = true;
            this.txtTenBoPhim.Size = new System.Drawing.Size(172, 33);
            this.txtTenBoPhim.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtTenBoPhim.TabIndex = 31;
            this.txtTenBoPhim.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtTenBoPhim.TextMarginBottom = 0;
            this.txtTenBoPhim.TextMarginLeft = 3;
            this.txtTenBoPhim.TextMarginTop = 0;
            this.txtTenBoPhim.TextPlaceholder = "Enter text";
            this.txtTenBoPhim.UseSystemPasswordChar = false;
            this.txtTenBoPhim.WordWrap = true;
            // 
            // txtMaBoPhim
            // 
            this.txtMaBoPhim.AcceptsReturn = false;
            this.txtMaBoPhim.AcceptsTab = false;
            this.txtMaBoPhim.AnimationSpeed = 200;
            this.txtMaBoPhim.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.txtMaBoPhim.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.txtMaBoPhim.BackColor = System.Drawing.Color.Transparent;
            this.txtMaBoPhim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("txtMaBoPhim.BackgroundImage")));
            this.txtMaBoPhim.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.txtMaBoPhim.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.txtMaBoPhim.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.txtMaBoPhim.BorderColorIdle = System.Drawing.Color.Silver;
            this.txtMaBoPhim.BorderRadius = 1;
            this.txtMaBoPhim.BorderThickness = 1;
            this.txtMaBoPhim.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.txtMaBoPhim.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaBoPhim.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.txtMaBoPhim.DefaultText = "";
            this.txtMaBoPhim.FillColor = System.Drawing.Color.White;
            this.txtMaBoPhim.HideSelection = true;
            this.txtMaBoPhim.IconLeft = null;
            this.txtMaBoPhim.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaBoPhim.IconPadding = 10;
            this.txtMaBoPhim.IconRight = null;
            this.txtMaBoPhim.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.txtMaBoPhim.Lines = new string[0];
            this.txtMaBoPhim.Location = new System.Drawing.Point(170, 64);
            this.txtMaBoPhim.MaxLength = 32767;
            this.txtMaBoPhim.MinimumSize = new System.Drawing.Size(1, 1);
            this.txtMaBoPhim.Modified = false;
            this.txtMaBoPhim.Multiline = false;
            this.txtMaBoPhim.Name = "txtMaBoPhim";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaBoPhim.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.txtMaBoPhim.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaBoPhim.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.txtMaBoPhim.OnIdleState = stateProperties28;
            this.txtMaBoPhim.Padding = new System.Windows.Forms.Padding(3);
            this.txtMaBoPhim.PasswordChar = '\0';
            this.txtMaBoPhim.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.txtMaBoPhim.PlaceholderText = "Enter text";
            this.txtMaBoPhim.ReadOnly = false;
            this.txtMaBoPhim.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.txtMaBoPhim.SelectedText = "";
            this.txtMaBoPhim.SelectionLength = 0;
            this.txtMaBoPhim.SelectionStart = 0;
            this.txtMaBoPhim.ShortcutsEnabled = true;
            this.txtMaBoPhim.Size = new System.Drawing.Size(172, 33);
            this.txtMaBoPhim.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.txtMaBoPhim.TabIndex = 29;
            this.txtMaBoPhim.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.txtMaBoPhim.TextMarginBottom = 0;
            this.txtMaBoPhim.TextMarginLeft = 3;
            this.txtMaBoPhim.TextMarginTop = 0;
            this.txtMaBoPhim.TextPlaceholder = "Enter text";
            this.txtMaBoPhim.UseSystemPasswordChar = false;
            this.txtMaBoPhim.WordWrap = true;
            // 
            // FBoPhim
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1361, 749);
            this.Controls.Add(this.flowLayoutPanel2);
            this.Controls.Add(this.flowLayoutPanel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FBoPhim";
            this.Text = "FBoPhim";
            this.Load += new System.EventHandler(this.FBoPhim_Load);
            ((System.ComponentModel.ISupportInitialize)(this.dgvBoPhim)).EndInit();
            this.flowLayoutPanel1.ResumeLayout(false);
            this.flowLayoutPanel2.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.bunifuShadowPanel1.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion
        private Bunifu.UI.WinForms.BunifuDataGridView dgvBoPhim;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel1;
        private System.Windows.Forms.FlowLayoutPanel flowLayoutPanel2;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private Bunifu.UI.WinForms.BunifuTextBox txtDienVien;
        private Bunifu.UI.WinForms.BunifuTextBox txtDaoDien;
        private Bunifu.UI.WinForms.BunifuTextBox txtThoiLuong;
        private Bunifu.UI.WinForms.BunifuTextBox txtTheLoai;
        private Bunifu.UI.WinForms.BunifuTextBox txtTenBoPhim;
        private Bunifu.UI.WinForms.BunifuTextBox txtMaBoPhim;
        private Bunifu.UI.WinForms.BunifuTextBox txtTomTat;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThem;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnUpdate;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnXoa;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label8;
        private System.Windows.Forms.Label label7;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Label label2;
    }
}