namespace DBMS1
{
    partial class FMain
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(FMain));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges8 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges9 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.panel1 = new System.Windows.Forms.Panel();
            this.bunifuShadowPanel1 = new Bunifu.UI.WinForms.BunifuShadowPanel();
            this.panel2 = new System.Windows.Forms.Panel();
            this.bunifuPanel1 = new Bunifu.UI.WinForms.BunifuPanel();
            this.bunifuPanel2 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pnShowTable = new System.Windows.Forms.Panel();
            this.bunifuPanel3 = new Bunifu.UI.WinForms.BunifuPanel();
            this.panel3 = new System.Windows.Forms.Panel();
            this.panel_Chan_Header = new System.Windows.Forms.Panel();
            this.bunifuPanel4 = new Bunifu.UI.WinForms.BunifuPanel();
            this.pnsideTab = new System.Windows.Forms.Panel();
            this.btnThoat = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLogin = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnChucNang7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnBoPhim = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnGheNgoi = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnVe = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnFnB = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnLichChieu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.btnPhongChieu = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.panel4 = new System.Windows.Forms.Panel();
            this.panel_Chan_Logo = new System.Windows.Forms.Panel();
            this.picBoxLogo = new System.Windows.Forms.PictureBox();
            this.panel_BenTrai = new System.Windows.Forms.Panel();
            this.panel1.SuspendLayout();
            this.bunifuShadowPanel1.SuspendLayout();
            this.panel2.SuspendLayout();
            this.bunifuPanel1.SuspendLayout();
            this.bunifuPanel2.SuspendLayout();
            this.bunifuPanel3.SuspendLayout();
            this.bunifuPanel4.SuspendLayout();
            this.pnsideTab.SuspendLayout();
            this.panel4.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.picBoxLogo)).BeginInit();
            this.SuspendLayout();
            // 
            // panel1
            // 
            this.panel1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(180)))), ((int)(((byte)(254)))));
            this.panel1.Controls.Add(this.bunifuShadowPanel1);
            this.panel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.panel1.Location = new System.Drawing.Point(0, 0);
            this.panel1.Margin = new System.Windows.Forms.Padding(4);
            this.panel1.Name = "panel1";
            this.panel1.Padding = new System.Windows.Forms.Padding(13, 12, 13, 12);
            this.panel1.Size = new System.Drawing.Size(1600, 862);
            this.panel1.TabIndex = 0;
            // 
            // bunifuShadowPanel1
            // 
            this.bunifuShadowPanel1.BackColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuShadowPanel1.BorderRadius = 1;
            this.bunifuShadowPanel1.BorderThickness = 1;
            this.bunifuShadowPanel1.Controls.Add(this.panel2);
            this.bunifuShadowPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuShadowPanel1.FillStyle = Bunifu.UI.WinForms.BunifuShadowPanel.FillStyles.Solid;
            this.bunifuShadowPanel1.GradientMode = Bunifu.UI.WinForms.BunifuShadowPanel.GradientModes.Vertical;
            this.bunifuShadowPanel1.Location = new System.Drawing.Point(13, 12);
            this.bunifuShadowPanel1.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuShadowPanel1.Name = "bunifuShadowPanel1";
            this.bunifuShadowPanel1.PanelColor = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(180)))), ((int)(((byte)(254)))));
            this.bunifuShadowPanel1.PanelColor2 = System.Drawing.Color.FromArgb(((int)(((byte)(116)))), ((int)(((byte)(180)))), ((int)(((byte)(254)))));
            this.bunifuShadowPanel1.ShadowColor = System.Drawing.Color.Black;
            this.bunifuShadowPanel1.ShadowDept = 2;
            this.bunifuShadowPanel1.ShadowDepth = 10;
            this.bunifuShadowPanel1.ShadowStyle = Bunifu.UI.WinForms.BunifuShadowPanel.ShadowStyles.Dropped;
            this.bunifuShadowPanel1.ShadowTopLeftVisible = false;
            this.bunifuShadowPanel1.Size = new System.Drawing.Size(1574, 838);
            this.bunifuShadowPanel1.Style = Bunifu.UI.WinForms.BunifuShadowPanel.BevelStyles.Flat;
            this.bunifuShadowPanel1.TabIndex = 0;
            // 
            // panel2
            // 
            this.panel2.Controls.Add(this.bunifuPanel1);
            this.panel2.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel2.Location = new System.Drawing.Point(0, 0);
            this.panel2.Margin = new System.Windows.Forms.Padding(4);
            this.panel2.Name = "panel2";
            this.panel2.Size = new System.Drawing.Size(1574, 814);
            this.panel2.TabIndex = 0;
            // 
            // bunifuPanel1
            // 
            this.bunifuPanel1.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel1.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel1.BackgroundImage")));
            this.bunifuPanel1.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel1.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel1.BorderRadius = 20;
            this.bunifuPanel1.BorderThickness = 1;
            this.bunifuPanel1.Controls.Add(this.bunifuPanel2);
            this.bunifuPanel1.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel1.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel1.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel1.Name = "bunifuPanel1";
            this.bunifuPanel1.ShowBorders = true;
            this.bunifuPanel1.Size = new System.Drawing.Size(1574, 814);
            this.bunifuPanel1.TabIndex = 0;
            // 
            // bunifuPanel2
            // 
            this.bunifuPanel2.BackgroundColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel2.BackgroundImage")));
            this.bunifuPanel2.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel2.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel2.BorderRadius = 3;
            this.bunifuPanel2.BorderThickness = 1;
            this.bunifuPanel2.Controls.Add(this.pnShowTable);
            this.bunifuPanel2.Controls.Add(this.bunifuPanel3);
            this.bunifuPanel2.Controls.Add(this.bunifuPanel4);
            this.bunifuPanel2.Controls.Add(this.panel_BenTrai);
            this.bunifuPanel2.Dock = System.Windows.Forms.DockStyle.Fill;
            this.bunifuPanel2.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel2.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel2.Name = "bunifuPanel2";
            this.bunifuPanel2.Padding = new System.Windows.Forms.Padding(0, 0, 3, 2);
            this.bunifuPanel2.ShowBorders = true;
            this.bunifuPanel2.Size = new System.Drawing.Size(1574, 814);
            this.bunifuPanel2.TabIndex = 0;
            // 
            // pnShowTable
            // 
            this.pnShowTable.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(235)))), ((int)(((byte)(247)))), ((int)(((byte)(255)))));
            this.pnShowTable.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnShowTable.Location = new System.Drawing.Point(210, 63);
            this.pnShowTable.Margin = new System.Windows.Forms.Padding(4);
            this.pnShowTable.Name = "pnShowTable";
            this.pnShowTable.Size = new System.Drawing.Size(1361, 749);
            this.pnShowTable.TabIndex = 3;
            // 
            // bunifuPanel3
            // 
            this.bunifuPanel3.BackgroundColor = System.Drawing.Color.FromArgb(((int)(((byte)(253)))), ((int)(((byte)(254)))), ((int)(((byte)(255)))));
            this.bunifuPanel3.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel3.BackgroundImage")));
            this.bunifuPanel3.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel3.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel3.BorderRadius = 20;
            this.bunifuPanel3.BorderThickness = 1;
            this.bunifuPanel3.Controls.Add(this.panel3);
            this.bunifuPanel3.Controls.Add(this.panel_Chan_Header);
            this.bunifuPanel3.Dock = System.Windows.Forms.DockStyle.Top;
            this.bunifuPanel3.Location = new System.Drawing.Point(210, 0);
            this.bunifuPanel3.Margin = new System.Windows.Forms.Padding(4);
            this.bunifuPanel3.Name = "bunifuPanel3";
            this.bunifuPanel3.ShowBorders = true;
            this.bunifuPanel3.Size = new System.Drawing.Size(1361, 63);
            this.bunifuPanel3.TabIndex = 7;
            // 
            // panel3
            // 
            this.panel3.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel3.Location = new System.Drawing.Point(0, 10);
            this.panel3.Margin = new System.Windows.Forms.Padding(4);
            this.panel3.Name = "panel3";
            this.panel3.Padding = new System.Windows.Forms.Padding(0, 0, 13, 0);
            this.panel3.Size = new System.Drawing.Size(1361, 51);
            this.panel3.TabIndex = 2;
            // 
            // panel_Chan_Header
            // 
            this.panel_Chan_Header.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(243)))), ((int)(((byte)(248)))));
            this.panel_Chan_Header.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.panel_Chan_Header.Location = new System.Drawing.Point(0, 61);
            this.panel_Chan_Header.Margin = new System.Windows.Forms.Padding(4);
            this.panel_Chan_Header.Name = "panel_Chan_Header";
            this.panel_Chan_Header.Size = new System.Drawing.Size(1361, 2);
            this.panel_Chan_Header.TabIndex = 0;
            // 
            // bunifuPanel4
            // 
            this.bunifuPanel4.BackgroundColor = System.Drawing.Color.White;
            this.bunifuPanel4.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bunifuPanel4.BackgroundImage")));
            this.bunifuPanel4.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Stretch;
            this.bunifuPanel4.BorderColor = System.Drawing.Color.Transparent;
            this.bunifuPanel4.BorderRadius = 20;
            this.bunifuPanel4.BorderThickness = 1;
            this.bunifuPanel4.Controls.Add(this.pnsideTab);
            this.bunifuPanel4.Controls.Add(this.panel4);
            this.bunifuPanel4.Dock = System.Windows.Forms.DockStyle.Left;
            this.bunifuPanel4.Location = new System.Drawing.Point(0, 0);
            this.bunifuPanel4.Margin = new System.Windows.Forms.Padding(0);
            this.bunifuPanel4.Name = "bunifuPanel4";
            this.bunifuPanel4.Padding = new System.Windows.Forms.Padding(4, 6, 0, 6);
            this.bunifuPanel4.ShowBorders = true;
            this.bunifuPanel4.Size = new System.Drawing.Size(210, 812);
            this.bunifuPanel4.TabIndex = 6;
            // 
            // pnsideTab
            // 
            this.pnsideTab.Controls.Add(this.btnThoat);
            this.pnsideTab.Controls.Add(this.btnLogin);
            this.pnsideTab.Controls.Add(this.btnChucNang7);
            this.pnsideTab.Controls.Add(this.btnBoPhim);
            this.pnsideTab.Controls.Add(this.btnGheNgoi);
            this.pnsideTab.Controls.Add(this.btnVe);
            this.pnsideTab.Controls.Add(this.btnFnB);
            this.pnsideTab.Controls.Add(this.btnLichChieu);
            this.pnsideTab.Controls.Add(this.btnPhongChieu);
            this.pnsideTab.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnsideTab.Location = new System.Drawing.Point(4, 141);
            this.pnsideTab.Name = "pnsideTab";
            this.pnsideTab.Size = new System.Drawing.Size(206, 665);
            this.pnsideTab.TabIndex = 1;
            // 
            // btnThoat
            // 
            this.btnThoat.AllowAnimations = true;
            this.btnThoat.AllowMouseEffects = true;
            this.btnThoat.AllowToggling = false;
            this.btnThoat.AnimationSpeed = 300;
            this.btnThoat.AutoGenerateColors = false;
            this.btnThoat.AutoRoundBorders = false;
            this.btnThoat.AutoSizeLeftIcon = true;
            this.btnThoat.AutoSizeRightIcon = true;
            this.btnThoat.BackColor = System.Drawing.Color.Transparent;
            this.btnThoat.BackColor1 = System.Drawing.Color.White;
            this.btnThoat.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnThoat.BackgroundImage")));
            this.btnThoat.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.ButtonText = "Thoát";
            this.btnThoat.ButtonTextMarginLeft = 0;
            this.btnThoat.ColorContrastOnClick = 45;
            this.btnThoat.ColorContrastOnHover = 45;
            this.btnThoat.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.btnThoat.CustomizableEdges = borderEdges1;
            this.btnThoat.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnThoat.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThoat.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThoat.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThoat.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.btnThoat.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnThoat.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnThoat.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnThoat.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThoat.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnThoat.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnThoat.IconMarginLeft = 11;
            this.btnThoat.IconPadding = 10;
            this.btnThoat.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnThoat.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnThoat.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnThoat.IconSize = 25;
            this.btnThoat.IdleBorderColor = System.Drawing.Color.White;
            this.btnThoat.IdleBorderRadius = 1;
            this.btnThoat.IdleBorderThickness = 1;
            this.btnThoat.IdleFillColor = System.Drawing.Color.White;
            this.btnThoat.IdleIconLeftImage = null;
            this.btnThoat.IdleIconRightImage = null;
            this.btnThoat.IndicateFocus = false;
            this.btnThoat.Location = new System.Drawing.Point(0, 617);
            this.btnThoat.Margin = new System.Windows.Forms.Padding(4);
            this.btnThoat.Name = "btnThoat";
            this.btnThoat.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnThoat.OnDisabledState.BorderRadius = 1;
            this.btnThoat.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.OnDisabledState.BorderThickness = 1;
            this.btnThoat.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnThoat.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnThoat.OnDisabledState.IconLeftImage = null;
            this.btnThoat.OnDisabledState.IconRightImage = null;
            this.btnThoat.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThoat.onHoverState.BorderRadius = 1;
            this.btnThoat.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.onHoverState.BorderThickness = 1;
            this.btnThoat.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnThoat.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnThoat.onHoverState.IconLeftImage = null;
            this.btnThoat.onHoverState.IconRightImage = null;
            this.btnThoat.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnThoat.OnIdleState.BorderRadius = 1;
            this.btnThoat.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.OnIdleState.BorderThickness = 1;
            this.btnThoat.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnThoat.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnThoat.OnIdleState.IconLeftImage = null;
            this.btnThoat.OnIdleState.IconRightImage = null;
            this.btnThoat.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThoat.OnPressedState.BorderRadius = 1;
            this.btnThoat.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnThoat.OnPressedState.BorderThickness = 1;
            this.btnThoat.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnThoat.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnThoat.OnPressedState.IconLeftImage = null;
            this.btnThoat.OnPressedState.IconRightImage = null;
            this.btnThoat.Size = new System.Drawing.Size(206, 48);
            this.btnThoat.TabIndex = 60;
            this.btnThoat.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnThoat.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnThoat.TextMarginLeft = 0;
            this.btnThoat.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnThoat.UseDefaultRadiusAndThickness = true;
            this.btnThoat.Click += new System.EventHandler(this.btn_Click);
            // 
            // btnLogin
            // 
            this.btnLogin.AllowAnimations = true;
            this.btnLogin.AllowMouseEffects = true;
            this.btnLogin.AllowToggling = false;
            this.btnLogin.AnimationSpeed = 300;
            this.btnLogin.AutoGenerateColors = false;
            this.btnLogin.AutoRoundBorders = false;
            this.btnLogin.AutoSizeLeftIcon = true;
            this.btnLogin.AutoSizeRightIcon = true;
            this.btnLogin.BackColor = System.Drawing.Color.Transparent;
            this.btnLogin.BackColor1 = System.Drawing.Color.White;
            this.btnLogin.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLogin.BackgroundImage")));
            this.btnLogin.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.ButtonText = "Đăng Nhập";
            this.btnLogin.ButtonTextMarginLeft = 0;
            this.btnLogin.ColorContrastOnClick = 45;
            this.btnLogin.ColorContrastOnHover = 45;
            this.btnLogin.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.btnLogin.CustomizableEdges = borderEdges2;
            this.btnLogin.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLogin.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogin.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogin.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogin.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnLogin.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnLogin.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnLogin.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnLogin.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogin.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogin.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLogin.IconMarginLeft = 11;
            this.btnLogin.IconPadding = 10;
            this.btnLogin.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLogin.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLogin.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLogin.IconSize = 25;
            this.btnLogin.IdleBorderColor = System.Drawing.Color.White;
            this.btnLogin.IdleBorderRadius = 1;
            this.btnLogin.IdleBorderThickness = 1;
            this.btnLogin.IdleFillColor = System.Drawing.Color.White;
            this.btnLogin.IdleIconLeftImage = null;
            this.btnLogin.IdleIconRightImage = null;
            this.btnLogin.IndicateFocus = false;
            this.btnLogin.Location = new System.Drawing.Point(0, 336);
            this.btnLogin.Margin = new System.Windows.Forms.Padding(4);
            this.btnLogin.Name = "btnLogin";
            this.btnLogin.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLogin.OnDisabledState.BorderRadius = 1;
            this.btnLogin.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnDisabledState.BorderThickness = 1;
            this.btnLogin.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLogin.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLogin.OnDisabledState.IconLeftImage = null;
            this.btnLogin.OnDisabledState.IconRightImage = null;
            this.btnLogin.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLogin.onHoverState.BorderRadius = 1;
            this.btnLogin.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.onHoverState.BorderThickness = 1;
            this.btnLogin.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLogin.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.onHoverState.IconLeftImage = null;
            this.btnLogin.onHoverState.IconRightImage = null;
            this.btnLogin.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnLogin.OnIdleState.BorderRadius = 1;
            this.btnLogin.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnIdleState.BorderThickness = 1;
            this.btnLogin.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnLogin.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnLogin.OnIdleState.IconLeftImage = null;
            this.btnLogin.OnIdleState.IconRightImage = null;
            this.btnLogin.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLogin.OnPressedState.BorderRadius = 1;
            this.btnLogin.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLogin.OnPressedState.BorderThickness = 1;
            this.btnLogin.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLogin.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLogin.OnPressedState.IconLeftImage = null;
            this.btnLogin.OnPressedState.IconRightImage = null;
            this.btnLogin.Size = new System.Drawing.Size(206, 48);
            this.btnLogin.TabIndex = 59;
            this.btnLogin.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLogin.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLogin.TextMarginLeft = 0;
            this.btnLogin.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLogin.UseDefaultRadiusAndThickness = true;
            this.btnLogin.Click += new System.EventHandler(this.btn_Click);
            // 
            // btnChucNang7
            // 
            this.btnChucNang7.AllowAnimations = true;
            this.btnChucNang7.AllowMouseEffects = true;
            this.btnChucNang7.AllowToggling = false;
            this.btnChucNang7.AnimationSpeed = 300;
            this.btnChucNang7.AutoGenerateColors = false;
            this.btnChucNang7.AutoRoundBorders = false;
            this.btnChucNang7.AutoSizeLeftIcon = true;
            this.btnChucNang7.AutoSizeRightIcon = true;
            this.btnChucNang7.BackColor = System.Drawing.Color.Transparent;
            this.btnChucNang7.BackColor1 = System.Drawing.Color.White;
            this.btnChucNang7.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnChucNang7.BackgroundImage")));
            this.btnChucNang7.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChucNang7.ButtonText = "Chức Năng 7";
            this.btnChucNang7.ButtonTextMarginLeft = 0;
            this.btnChucNang7.ColorContrastOnClick = 45;
            this.btnChucNang7.ColorContrastOnHover = 45;
            this.btnChucNang7.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.btnChucNang7.CustomizableEdges = borderEdges3;
            this.btnChucNang7.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnChucNang7.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChucNang7.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChucNang7.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChucNang7.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnChucNang7.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnChucNang7.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnChucNang7.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnChucNang7.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChucNang7.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnChucNang7.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnChucNang7.IconMarginLeft = 11;
            this.btnChucNang7.IconPadding = 10;
            this.btnChucNang7.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnChucNang7.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnChucNang7.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnChucNang7.IconSize = 25;
            this.btnChucNang7.IdleBorderColor = System.Drawing.Color.White;
            this.btnChucNang7.IdleBorderRadius = 1;
            this.btnChucNang7.IdleBorderThickness = 1;
            this.btnChucNang7.IdleFillColor = System.Drawing.Color.White;
            this.btnChucNang7.IdleIconLeftImage = null;
            this.btnChucNang7.IdleIconRightImage = null;
            this.btnChucNang7.IndicateFocus = false;
            this.btnChucNang7.Location = new System.Drawing.Point(0, 288);
            this.btnChucNang7.Margin = new System.Windows.Forms.Padding(4);
            this.btnChucNang7.Name = "btnChucNang7";
            this.btnChucNang7.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnChucNang7.OnDisabledState.BorderRadius = 1;
            this.btnChucNang7.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChucNang7.OnDisabledState.BorderThickness = 1;
            this.btnChucNang7.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnChucNang7.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnChucNang7.OnDisabledState.IconLeftImage = null;
            this.btnChucNang7.OnDisabledState.IconRightImage = null;
            this.btnChucNang7.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChucNang7.onHoverState.BorderRadius = 1;
            this.btnChucNang7.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChucNang7.onHoverState.BorderThickness = 1;
            this.btnChucNang7.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnChucNang7.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnChucNang7.onHoverState.IconLeftImage = null;
            this.btnChucNang7.onHoverState.IconRightImage = null;
            this.btnChucNang7.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnChucNang7.OnIdleState.BorderRadius = 1;
            this.btnChucNang7.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChucNang7.OnIdleState.BorderThickness = 1;
            this.btnChucNang7.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnChucNang7.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnChucNang7.OnIdleState.IconLeftImage = null;
            this.btnChucNang7.OnIdleState.IconRightImage = null;
            this.btnChucNang7.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChucNang7.OnPressedState.BorderRadius = 1;
            this.btnChucNang7.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnChucNang7.OnPressedState.BorderThickness = 1;
            this.btnChucNang7.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnChucNang7.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnChucNang7.OnPressedState.IconLeftImage = null;
            this.btnChucNang7.OnPressedState.IconRightImage = null;
            this.btnChucNang7.Size = new System.Drawing.Size(206, 48);
            this.btnChucNang7.TabIndex = 58;
            this.btnChucNang7.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnChucNang7.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnChucNang7.TextMarginLeft = 0;
            this.btnChucNang7.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnChucNang7.UseDefaultRadiusAndThickness = true;
            // 
            // btnBoPhim
            // 
            this.btnBoPhim.AllowAnimations = true;
            this.btnBoPhim.AllowMouseEffects = true;
            this.btnBoPhim.AllowToggling = false;
            this.btnBoPhim.AnimationSpeed = 300;
            this.btnBoPhim.AutoGenerateColors = false;
            this.btnBoPhim.AutoRoundBorders = false;
            this.btnBoPhim.AutoSizeLeftIcon = true;
            this.btnBoPhim.AutoSizeRightIcon = true;
            this.btnBoPhim.BackColor = System.Drawing.Color.Transparent;
            this.btnBoPhim.BackColor1 = System.Drawing.Color.White;
            this.btnBoPhim.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnBoPhim.BackgroundImage")));
            this.btnBoPhim.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoPhim.ButtonText = "Bộ Phim";
            this.btnBoPhim.ButtonTextMarginLeft = 0;
            this.btnBoPhim.ColorContrastOnClick = 45;
            this.btnBoPhim.ColorContrastOnHover = 45;
            this.btnBoPhim.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            this.btnBoPhim.CustomizableEdges = borderEdges4;
            this.btnBoPhim.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnBoPhim.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBoPhim.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBoPhim.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBoPhim.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnBoPhim.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnBoPhim.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnBoPhim.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnBoPhim.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBoPhim.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnBoPhim.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnBoPhim.IconMarginLeft = 11;
            this.btnBoPhim.IconPadding = 10;
            this.btnBoPhim.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnBoPhim.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnBoPhim.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnBoPhim.IconSize = 25;
            this.btnBoPhim.IdleBorderColor = System.Drawing.Color.White;
            this.btnBoPhim.IdleBorderRadius = 1;
            this.btnBoPhim.IdleBorderThickness = 1;
            this.btnBoPhim.IdleFillColor = System.Drawing.Color.White;
            this.btnBoPhim.IdleIconLeftImage = null;
            this.btnBoPhim.IdleIconRightImage = null;
            this.btnBoPhim.IndicateFocus = false;
            this.btnBoPhim.Location = new System.Drawing.Point(0, 240);
            this.btnBoPhim.Margin = new System.Windows.Forms.Padding(4);
            this.btnBoPhim.Name = "btnBoPhim";
            this.btnBoPhim.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnBoPhim.OnDisabledState.BorderRadius = 1;
            this.btnBoPhim.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoPhim.OnDisabledState.BorderThickness = 1;
            this.btnBoPhim.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnBoPhim.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnBoPhim.OnDisabledState.IconLeftImage = null;
            this.btnBoPhim.OnDisabledState.IconRightImage = null;
            this.btnBoPhim.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBoPhim.onHoverState.BorderRadius = 1;
            this.btnBoPhim.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoPhim.onHoverState.BorderThickness = 1;
            this.btnBoPhim.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnBoPhim.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnBoPhim.onHoverState.IconLeftImage = null;
            this.btnBoPhim.onHoverState.IconRightImage = null;
            this.btnBoPhim.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnBoPhim.OnIdleState.BorderRadius = 1;
            this.btnBoPhim.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoPhim.OnIdleState.BorderThickness = 1;
            this.btnBoPhim.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnBoPhim.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnBoPhim.OnIdleState.IconLeftImage = null;
            this.btnBoPhim.OnIdleState.IconRightImage = null;
            this.btnBoPhim.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBoPhim.OnPressedState.BorderRadius = 1;
            this.btnBoPhim.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnBoPhim.OnPressedState.BorderThickness = 1;
            this.btnBoPhim.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnBoPhim.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnBoPhim.OnPressedState.IconLeftImage = null;
            this.btnBoPhim.OnPressedState.IconRightImage = null;
            this.btnBoPhim.Size = new System.Drawing.Size(206, 48);
            this.btnBoPhim.TabIndex = 57;
            this.btnBoPhim.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnBoPhim.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnBoPhim.TextMarginLeft = 0;
            this.btnBoPhim.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnBoPhim.UseDefaultRadiusAndThickness = true;
            this.btnBoPhim.Click += new System.EventHandler(this.btn_Click);
            // 
            // btnGheNgoi
            // 
            this.btnGheNgoi.AllowAnimations = true;
            this.btnGheNgoi.AllowMouseEffects = true;
            this.btnGheNgoi.AllowToggling = false;
            this.btnGheNgoi.AnimationSpeed = 300;
            this.btnGheNgoi.AutoGenerateColors = false;
            this.btnGheNgoi.AutoRoundBorders = false;
            this.btnGheNgoi.AutoSizeLeftIcon = true;
            this.btnGheNgoi.AutoSizeRightIcon = true;
            this.btnGheNgoi.BackColor = System.Drawing.Color.Transparent;
            this.btnGheNgoi.BackColor1 = System.Drawing.Color.White;
            this.btnGheNgoi.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnGheNgoi.BackgroundImage")));
            this.btnGheNgoi.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGheNgoi.ButtonText = "Ghế Ngồi";
            this.btnGheNgoi.ButtonTextMarginLeft = 0;
            this.btnGheNgoi.ColorContrastOnClick = 45;
            this.btnGheNgoi.ColorContrastOnHover = 45;
            this.btnGheNgoi.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            this.btnGheNgoi.CustomizableEdges = borderEdges5;
            this.btnGheNgoi.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnGheNgoi.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGheNgoi.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGheNgoi.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGheNgoi.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnGheNgoi.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnGheNgoi.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnGheNgoi.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnGheNgoi.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGheNgoi.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnGheNgoi.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnGheNgoi.IconMarginLeft = 11;
            this.btnGheNgoi.IconPadding = 10;
            this.btnGheNgoi.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnGheNgoi.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnGheNgoi.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnGheNgoi.IconSize = 25;
            this.btnGheNgoi.IdleBorderColor = System.Drawing.Color.White;
            this.btnGheNgoi.IdleBorderRadius = 1;
            this.btnGheNgoi.IdleBorderThickness = 1;
            this.btnGheNgoi.IdleFillColor = System.Drawing.Color.White;
            this.btnGheNgoi.IdleIconLeftImage = null;
            this.btnGheNgoi.IdleIconRightImage = null;
            this.btnGheNgoi.IndicateFocus = false;
            this.btnGheNgoi.Location = new System.Drawing.Point(0, 192);
            this.btnGheNgoi.Margin = new System.Windows.Forms.Padding(4);
            this.btnGheNgoi.Name = "btnGheNgoi";
            this.btnGheNgoi.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnGheNgoi.OnDisabledState.BorderRadius = 1;
            this.btnGheNgoi.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGheNgoi.OnDisabledState.BorderThickness = 1;
            this.btnGheNgoi.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnGheNgoi.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnGheNgoi.OnDisabledState.IconLeftImage = null;
            this.btnGheNgoi.OnDisabledState.IconRightImage = null;
            this.btnGheNgoi.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnGheNgoi.onHoverState.BorderRadius = 1;
            this.btnGheNgoi.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGheNgoi.onHoverState.BorderThickness = 1;
            this.btnGheNgoi.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnGheNgoi.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnGheNgoi.onHoverState.IconLeftImage = null;
            this.btnGheNgoi.onHoverState.IconRightImage = null;
            this.btnGheNgoi.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnGheNgoi.OnIdleState.BorderRadius = 1;
            this.btnGheNgoi.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGheNgoi.OnIdleState.BorderThickness = 1;
            this.btnGheNgoi.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnGheNgoi.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnGheNgoi.OnIdleState.IconLeftImage = null;
            this.btnGheNgoi.OnIdleState.IconRightImage = null;
            this.btnGheNgoi.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnGheNgoi.OnPressedState.BorderRadius = 1;
            this.btnGheNgoi.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnGheNgoi.OnPressedState.BorderThickness = 1;
            this.btnGheNgoi.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnGheNgoi.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnGheNgoi.OnPressedState.IconLeftImage = null;
            this.btnGheNgoi.OnPressedState.IconRightImage = null;
            this.btnGheNgoi.Size = new System.Drawing.Size(206, 48);
            this.btnGheNgoi.TabIndex = 56;
            this.btnGheNgoi.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnGheNgoi.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnGheNgoi.TextMarginLeft = 0;
            this.btnGheNgoi.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnGheNgoi.UseDefaultRadiusAndThickness = true;
            this.btnGheNgoi.Click += new System.EventHandler(this.btn_Click);
            // 
            // btnVe
            // 
            this.btnVe.AllowAnimations = true;
            this.btnVe.AllowMouseEffects = true;
            this.btnVe.AllowToggling = false;
            this.btnVe.AnimationSpeed = 300;
            this.btnVe.AutoGenerateColors = false;
            this.btnVe.AutoRoundBorders = false;
            this.btnVe.AutoSizeLeftIcon = true;
            this.btnVe.AutoSizeRightIcon = true;
            this.btnVe.BackColor = System.Drawing.Color.Transparent;
            this.btnVe.BackColor1 = System.Drawing.Color.White;
            this.btnVe.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnVe.BackgroundImage")));
            this.btnVe.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVe.ButtonText = "Vé";
            this.btnVe.ButtonTextMarginLeft = 0;
            this.btnVe.ColorContrastOnClick = 45;
            this.btnVe.ColorContrastOnHover = 45;
            this.btnVe.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            this.btnVe.CustomizableEdges = borderEdges6;
            this.btnVe.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnVe.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVe.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVe.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVe.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnVe.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnVe.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnVe.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnVe.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVe.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnVe.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnVe.IconMarginLeft = 11;
            this.btnVe.IconPadding = 10;
            this.btnVe.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnVe.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnVe.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnVe.IconSize = 25;
            this.btnVe.IdleBorderColor = System.Drawing.Color.White;
            this.btnVe.IdleBorderRadius = 1;
            this.btnVe.IdleBorderThickness = 1;
            this.btnVe.IdleFillColor = System.Drawing.Color.White;
            this.btnVe.IdleIconLeftImage = null;
            this.btnVe.IdleIconRightImage = null;
            this.btnVe.IndicateFocus = false;
            this.btnVe.Location = new System.Drawing.Point(0, 144);
            this.btnVe.Margin = new System.Windows.Forms.Padding(4);
            this.btnVe.Name = "btnVe";
            this.btnVe.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnVe.OnDisabledState.BorderRadius = 1;
            this.btnVe.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVe.OnDisabledState.BorderThickness = 1;
            this.btnVe.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnVe.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnVe.OnDisabledState.IconLeftImage = null;
            this.btnVe.OnDisabledState.IconRightImage = null;
            this.btnVe.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVe.onHoverState.BorderRadius = 1;
            this.btnVe.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVe.onHoverState.BorderThickness = 1;
            this.btnVe.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnVe.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnVe.onHoverState.IconLeftImage = null;
            this.btnVe.onHoverState.IconRightImage = null;
            this.btnVe.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnVe.OnIdleState.BorderRadius = 1;
            this.btnVe.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVe.OnIdleState.BorderThickness = 1;
            this.btnVe.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnVe.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnVe.OnIdleState.IconLeftImage = null;
            this.btnVe.OnIdleState.IconRightImage = null;
            this.btnVe.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVe.OnPressedState.BorderRadius = 1;
            this.btnVe.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnVe.OnPressedState.BorderThickness = 1;
            this.btnVe.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnVe.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnVe.OnPressedState.IconLeftImage = null;
            this.btnVe.OnPressedState.IconRightImage = null;
            this.btnVe.Size = new System.Drawing.Size(206, 48);
            this.btnVe.TabIndex = 55;
            this.btnVe.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnVe.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnVe.TextMarginLeft = 0;
            this.btnVe.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnVe.UseDefaultRadiusAndThickness = true;
            this.btnVe.Click += new System.EventHandler(this.btn_Click);
            // 
            // btnFnB
            // 
            this.btnFnB.AllowAnimations = true;
            this.btnFnB.AllowMouseEffects = true;
            this.btnFnB.AllowToggling = false;
            this.btnFnB.AnimationSpeed = 300;
            this.btnFnB.AutoGenerateColors = false;
            this.btnFnB.AutoRoundBorders = false;
            this.btnFnB.AutoSizeLeftIcon = true;
            this.btnFnB.AutoSizeRightIcon = true;
            this.btnFnB.BackColor = System.Drawing.Color.Transparent;
            this.btnFnB.BackColor1 = System.Drawing.Color.White;
            this.btnFnB.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnFnB.BackgroundImage")));
            this.btnFnB.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFnB.ButtonText = "Food and Baverage";
            this.btnFnB.ButtonTextMarginLeft = 0;
            this.btnFnB.ColorContrastOnClick = 45;
            this.btnFnB.ColorContrastOnHover = 45;
            this.btnFnB.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            this.btnFnB.CustomizableEdges = borderEdges7;
            this.btnFnB.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnFnB.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFnB.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFnB.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFnB.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnFnB.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnFnB.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnFnB.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnFnB.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFnB.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnFnB.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnFnB.IconMarginLeft = 11;
            this.btnFnB.IconPadding = 10;
            this.btnFnB.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnFnB.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnFnB.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnFnB.IconSize = 25;
            this.btnFnB.IdleBorderColor = System.Drawing.Color.White;
            this.btnFnB.IdleBorderRadius = 1;
            this.btnFnB.IdleBorderThickness = 1;
            this.btnFnB.IdleFillColor = System.Drawing.Color.White;
            this.btnFnB.IdleIconLeftImage = null;
            this.btnFnB.IdleIconRightImage = null;
            this.btnFnB.IndicateFocus = false;
            this.btnFnB.Location = new System.Drawing.Point(0, 96);
            this.btnFnB.Margin = new System.Windows.Forms.Padding(4);
            this.btnFnB.Name = "btnFnB";
            this.btnFnB.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnFnB.OnDisabledState.BorderRadius = 1;
            this.btnFnB.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFnB.OnDisabledState.BorderThickness = 1;
            this.btnFnB.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnFnB.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnFnB.OnDisabledState.IconLeftImage = null;
            this.btnFnB.OnDisabledState.IconRightImage = null;
            this.btnFnB.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFnB.onHoverState.BorderRadius = 1;
            this.btnFnB.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFnB.onHoverState.BorderThickness = 1;
            this.btnFnB.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnFnB.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnFnB.onHoverState.IconLeftImage = null;
            this.btnFnB.onHoverState.IconRightImage = null;
            this.btnFnB.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnFnB.OnIdleState.BorderRadius = 1;
            this.btnFnB.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFnB.OnIdleState.BorderThickness = 1;
            this.btnFnB.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnFnB.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnFnB.OnIdleState.IconLeftImage = null;
            this.btnFnB.OnIdleState.IconRightImage = null;
            this.btnFnB.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFnB.OnPressedState.BorderRadius = 1;
            this.btnFnB.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnFnB.OnPressedState.BorderThickness = 1;
            this.btnFnB.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnFnB.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnFnB.OnPressedState.IconLeftImage = null;
            this.btnFnB.OnPressedState.IconRightImage = null;
            this.btnFnB.Size = new System.Drawing.Size(206, 48);
            this.btnFnB.TabIndex = 54;
            this.btnFnB.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnFnB.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnFnB.TextMarginLeft = 0;
            this.btnFnB.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnFnB.UseDefaultRadiusAndThickness = true;
            this.btnFnB.Click += new System.EventHandler(this.btn_Click);
            // 
            // btnLichChieu
            // 
            this.btnLichChieu.AllowAnimations = true;
            this.btnLichChieu.AllowMouseEffects = true;
            this.btnLichChieu.AllowToggling = false;
            this.btnLichChieu.AnimationSpeed = 300;
            this.btnLichChieu.AutoGenerateColors = false;
            this.btnLichChieu.AutoRoundBorders = false;
            this.btnLichChieu.AutoSizeLeftIcon = true;
            this.btnLichChieu.AutoSizeRightIcon = true;
            this.btnLichChieu.BackColor = System.Drawing.Color.Transparent;
            this.btnLichChieu.BackColor1 = System.Drawing.Color.White;
            this.btnLichChieu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnLichChieu.BackgroundImage")));
            this.btnLichChieu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichChieu.ButtonText = "Lịch Chiếu";
            this.btnLichChieu.ButtonTextMarginLeft = 0;
            this.btnLichChieu.ColorContrastOnClick = 45;
            this.btnLichChieu.ColorContrastOnHover = 45;
            this.btnLichChieu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges8.BottomLeft = true;
            borderEdges8.BottomRight = true;
            borderEdges8.TopLeft = true;
            borderEdges8.TopRight = true;
            this.btnLichChieu.CustomizableEdges = borderEdges8;
            this.btnLichChieu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnLichChieu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLichChieu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLichChieu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLichChieu.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnLichChieu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnLichChieu.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnLichChieu.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnLichChieu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLichChieu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnLichChieu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnLichChieu.IconMarginLeft = 11;
            this.btnLichChieu.IconPadding = 10;
            this.btnLichChieu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnLichChieu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnLichChieu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnLichChieu.IconSize = 25;
            this.btnLichChieu.IdleBorderColor = System.Drawing.Color.White;
            this.btnLichChieu.IdleBorderRadius = 1;
            this.btnLichChieu.IdleBorderThickness = 1;
            this.btnLichChieu.IdleFillColor = System.Drawing.Color.White;
            this.btnLichChieu.IdleIconLeftImage = null;
            this.btnLichChieu.IdleIconRightImage = null;
            this.btnLichChieu.IndicateFocus = false;
            this.btnLichChieu.Location = new System.Drawing.Point(0, 48);
            this.btnLichChieu.Margin = new System.Windows.Forms.Padding(4);
            this.btnLichChieu.Name = "btnLichChieu";
            this.btnLichChieu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnLichChieu.OnDisabledState.BorderRadius = 1;
            this.btnLichChieu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichChieu.OnDisabledState.BorderThickness = 1;
            this.btnLichChieu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnLichChieu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnLichChieu.OnDisabledState.IconLeftImage = null;
            this.btnLichChieu.OnDisabledState.IconRightImage = null;
            this.btnLichChieu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLichChieu.onHoverState.BorderRadius = 1;
            this.btnLichChieu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichChieu.onHoverState.BorderThickness = 1;
            this.btnLichChieu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnLichChieu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnLichChieu.onHoverState.IconLeftImage = null;
            this.btnLichChieu.onHoverState.IconRightImage = null;
            this.btnLichChieu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnLichChieu.OnIdleState.BorderRadius = 1;
            this.btnLichChieu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichChieu.OnIdleState.BorderThickness = 1;
            this.btnLichChieu.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnLichChieu.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnLichChieu.OnIdleState.IconLeftImage = null;
            this.btnLichChieu.OnIdleState.IconRightImage = null;
            this.btnLichChieu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLichChieu.OnPressedState.BorderRadius = 1;
            this.btnLichChieu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnLichChieu.OnPressedState.BorderThickness = 1;
            this.btnLichChieu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnLichChieu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnLichChieu.OnPressedState.IconLeftImage = null;
            this.btnLichChieu.OnPressedState.IconRightImage = null;
            this.btnLichChieu.Size = new System.Drawing.Size(206, 48);
            this.btnLichChieu.TabIndex = 53;
            this.btnLichChieu.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnLichChieu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnLichChieu.TextMarginLeft = 0;
            this.btnLichChieu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnLichChieu.UseDefaultRadiusAndThickness = true;
            this.btnLichChieu.Click += new System.EventHandler(this.btn_Click);
            // 
            // btnPhongChieu
            // 
            this.btnPhongChieu.AllowAnimations = true;
            this.btnPhongChieu.AllowMouseEffects = true;
            this.btnPhongChieu.AllowToggling = false;
            this.btnPhongChieu.AnimationSpeed = 300;
            this.btnPhongChieu.AutoGenerateColors = false;
            this.btnPhongChieu.AutoRoundBorders = false;
            this.btnPhongChieu.AutoSizeLeftIcon = true;
            this.btnPhongChieu.AutoSizeRightIcon = true;
            this.btnPhongChieu.BackColor = System.Drawing.Color.Transparent;
            this.btnPhongChieu.BackColor1 = System.Drawing.Color.White;
            this.btnPhongChieu.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("btnPhongChieu.BackgroundImage")));
            this.btnPhongChieu.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhongChieu.ButtonText = "Phòng Chiếu";
            this.btnPhongChieu.ButtonTextMarginLeft = 0;
            this.btnPhongChieu.ColorContrastOnClick = 45;
            this.btnPhongChieu.ColorContrastOnHover = 45;
            this.btnPhongChieu.Cursor = System.Windows.Forms.Cursors.Hand;
            borderEdges9.BottomLeft = true;
            borderEdges9.BottomRight = true;
            borderEdges9.TopLeft = true;
            borderEdges9.TopRight = true;
            this.btnPhongChieu.CustomizableEdges = borderEdges9;
            this.btnPhongChieu.DialogResult = System.Windows.Forms.DialogResult.None;
            this.btnPhongChieu.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPhongChieu.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPhongChieu.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPhongChieu.Dock = System.Windows.Forms.DockStyle.Top;
            this.btnPhongChieu.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Disabled;
            this.btnPhongChieu.Font = new System.Drawing.Font("Bahnschrift SemiBold", 12F, System.Drawing.FontStyle.Bold);
            this.btnPhongChieu.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnPhongChieu.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPhongChieu.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.btnPhongChieu.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.btnPhongChieu.IconMarginLeft = 11;
            this.btnPhongChieu.IconPadding = 10;
            this.btnPhongChieu.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.btnPhongChieu.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.btnPhongChieu.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.btnPhongChieu.IconSize = 25;
            this.btnPhongChieu.IdleBorderColor = System.Drawing.Color.White;
            this.btnPhongChieu.IdleBorderRadius = 1;
            this.btnPhongChieu.IdleBorderThickness = 1;
            this.btnPhongChieu.IdleFillColor = System.Drawing.Color.White;
            this.btnPhongChieu.IdleIconLeftImage = null;
            this.btnPhongChieu.IdleIconRightImage = null;
            this.btnPhongChieu.IndicateFocus = false;
            this.btnPhongChieu.Location = new System.Drawing.Point(0, 0);
            this.btnPhongChieu.Margin = new System.Windows.Forms.Padding(4);
            this.btnPhongChieu.Name = "btnPhongChieu";
            this.btnPhongChieu.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.btnPhongChieu.OnDisabledState.BorderRadius = 1;
            this.btnPhongChieu.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhongChieu.OnDisabledState.BorderThickness = 1;
            this.btnPhongChieu.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.btnPhongChieu.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.btnPhongChieu.OnDisabledState.IconLeftImage = null;
            this.btnPhongChieu.OnDisabledState.IconRightImage = null;
            this.btnPhongChieu.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPhongChieu.onHoverState.BorderRadius = 1;
            this.btnPhongChieu.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhongChieu.onHoverState.BorderThickness = 1;
            this.btnPhongChieu.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.btnPhongChieu.onHoverState.ForeColor = System.Drawing.Color.White;
            this.btnPhongChieu.onHoverState.IconLeftImage = null;
            this.btnPhongChieu.onHoverState.IconRightImage = null;
            this.btnPhongChieu.OnIdleState.BorderColor = System.Drawing.Color.White;
            this.btnPhongChieu.OnIdleState.BorderRadius = 1;
            this.btnPhongChieu.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhongChieu.OnIdleState.BorderThickness = 1;
            this.btnPhongChieu.OnIdleState.FillColor = System.Drawing.Color.White;
            this.btnPhongChieu.OnIdleState.ForeColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.btnPhongChieu.OnIdleState.IconLeftImage = null;
            this.btnPhongChieu.OnIdleState.IconRightImage = null;
            this.btnPhongChieu.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPhongChieu.OnPressedState.BorderRadius = 1;
            this.btnPhongChieu.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.btnPhongChieu.OnPressedState.BorderThickness = 1;
            this.btnPhongChieu.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.btnPhongChieu.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.btnPhongChieu.OnPressedState.IconLeftImage = null;
            this.btnPhongChieu.OnPressedState.IconRightImage = null;
            this.btnPhongChieu.Size = new System.Drawing.Size(206, 48);
            this.btnPhongChieu.TabIndex = 52;
            this.btnPhongChieu.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.btnPhongChieu.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.btnPhongChieu.TextMarginLeft = 0;
            this.btnPhongChieu.TextPadding = new System.Windows.Forms.Padding(0);
            this.btnPhongChieu.UseDefaultRadiusAndThickness = true;
            this.btnPhongChieu.Click += new System.EventHandler(this.btn_Click);
            // 
            // panel4
            // 
            this.panel4.Controls.Add(this.panel_Chan_Logo);
            this.panel4.Controls.Add(this.picBoxLogo);
            this.panel4.Dock = System.Windows.Forms.DockStyle.Top;
            this.panel4.Location = new System.Drawing.Point(4, 6);
            this.panel4.Name = "panel4";
            this.panel4.Size = new System.Drawing.Size(206, 135);
            this.panel4.TabIndex = 0;
            // 
            // panel_Chan_Logo
            // 
            this.panel_Chan_Logo.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(224)))), ((int)(((byte)(224)))), ((int)(((byte)(224)))));
            this.panel_Chan_Logo.Location = new System.Drawing.Point(6, 121);
            this.panel_Chan_Logo.Margin = new System.Windows.Forms.Padding(4);
            this.panel_Chan_Logo.Name = "panel_Chan_Logo";
            this.panel_Chan_Logo.Size = new System.Drawing.Size(200, 6);
            this.panel_Chan_Logo.TabIndex = 3;
            // 
            // picBoxLogo
            // 
            this.picBoxLogo.BackColor = System.Drawing.Color.White;
            this.picBoxLogo.BackgroundImageLayout = System.Windows.Forms.ImageLayout.Center;
            this.picBoxLogo.Image = global::DBMS1.Properties.Resources.lg_vinema;
            this.picBoxLogo.Location = new System.Drawing.Point(4, 4);
            this.picBoxLogo.Margin = new System.Windows.Forms.Padding(4);
            this.picBoxLogo.Name = "picBoxLogo";
            this.picBoxLogo.Size = new System.Drawing.Size(200, 73);
            this.picBoxLogo.SizeMode = System.Windows.Forms.PictureBoxSizeMode.StretchImage;
            this.picBoxLogo.TabIndex = 4;
            this.picBoxLogo.TabStop = false;
            // 
            // panel_BenTrai
            // 
            this.panel_BenTrai.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(244)))), ((int)(((byte)(243)))), ((int)(((byte)(248)))));
            this.panel_BenTrai.Location = new System.Drawing.Point(211, 1);
            this.panel_BenTrai.Margin = new System.Windows.Forms.Padding(4);
            this.panel_BenTrai.Name = "panel_BenTrai";
            this.panel_BenTrai.Size = new System.Drawing.Size(3, 809);
            this.panel_BenTrai.TabIndex = 1;
            // 
            // FMain
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1600, 862);
            this.Controls.Add(this.panel1);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Name = "FMain";
            this.Text = "FMain";
            this.panel1.ResumeLayout(false);
            this.bunifuShadowPanel1.ResumeLayout(false);
            this.panel2.ResumeLayout(false);
            this.bunifuPanel1.ResumeLayout(false);
            this.bunifuPanel2.ResumeLayout(false);
            this.bunifuPanel3.ResumeLayout(false);
            this.bunifuPanel4.ResumeLayout(false);
            this.pnsideTab.ResumeLayout(false);
            this.panel4.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.picBoxLogo)).EndInit();
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.Panel panel1;
        private Bunifu.UI.WinForms.BunifuShadowPanel bunifuShadowPanel1;
        private System.Windows.Forms.Panel panel2;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel1;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel2;
        private System.Windows.Forms.Panel pnShowTable;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel3;
        private System.Windows.Forms.Panel panel3;
        private System.Windows.Forms.Panel panel_Chan_Header;
        private Bunifu.UI.WinForms.BunifuPanel bunifuPanel4;
        private System.Windows.Forms.Panel pnsideTab;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLogin;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnChucNang7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnBoPhim;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnGheNgoi;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnVe;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnFnB;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnLichChieu;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnPhongChieu;
        private System.Windows.Forms.Panel panel4;
        private System.Windows.Forms.Panel panel_Chan_Logo;
        private System.Windows.Forms.PictureBox picBoxLogo;
        private System.Windows.Forms.Panel panel_BenTrai;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton btnThoat;
    }
}